language: node_js
node_js:
  - 6.2.2
services:
  - redis-server
before_install:
  - redis-cli "hset 1 test success"
before_script:
  - npm run lint
script:
  - NODE_ENV=test node server/master.js 
  - npm test
